### PR TITLE
Add: Aliases copypasta

### PR DESCRIPTION
**Pull request by jeyemwey**
I like using small tools like imagemagick in containers, so I have set up a bunch of aliases for the different IM commands.

### CODE REVIEW

**Comment by madhead** [comment]
Thank you for the contribution, looks nice. Just a few notes.

1. I think that all that hustle with `/src` and `/out` and working directory is not needed for aliases, maybe remove it? Let's leave only the vital options.
2. Probably rename the name alias to not contain repo/image owner? Like `dockerImagemagick`?

**Comment by jeyemwey** [comment]
To your first point: We could use another approach by defining `WORKDIR` inside the Dockerfile. This would eliminate the need for `/src` and `/out` in your other examples, too. (If you assume that most people use $(pwd)==/src==/out). I will prepare a PR for this, earliest on Saturday.

To the second point: Sure, this was just what came to my head first.

**Comment by madhead** [comment]
In a simple case like this we need only `-w /something` and `-v $(pwd):/something`, no need to have two directories?

**Comment by jeyemwey** [comment]
If the Dockerfile contains `WORKDIR /src', the call can be as short as

`docker run -it --rm -v $(pwd):/src madhead/imagemagick convert in.jpg out.png`

**Comment by madhead** [comment]
Ok. Then just let's not mount `$(pwd):/out` and leave workdir as an option: do not want to change Dockerfile for that :)

**Comment by jeyemwey** [comment]
I have crushed my git repo, I will push another PR soon.

**Pull request closed without merging**
